apiVersion: v1
kind: BuildConfig
metadata:
  name: tt-le.java-liberty-app
  labels:
    app: java-liberty-app
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/tt-le/java-liberty-app.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: java-liberty-app
        - name: BRANCH
          value: master
